### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by astone123** [gametrunk-team/gametrunk#52]

**Comment by ghochard42six** [comment]
I suggest adding a screenshot.

**Comment by astone123** [comment]
Whether or not there is content on the screen, the footer needs to be at the bottom of the window. If there is more content than fits the screen, the footer needs to be at the very bottom of the content, only to be in view when the user scrolls down to the bottom of the content.

Below is the current footer position.

<img width="1440" alt="screen shot 2016-07-29 at 2 26 37 pm" src="https://cloud.githubusercontent.com/assets/14275198/17259232/896897b4-5598-11e6-8a8c-ef9502c47f9c.png">
